(() => {
  const $=id=>document.getElementById(id),num=t=>Number(String(t||'').match(/[\d.]+/)?.[0]||0);
  const isMiddleton=location.pathname.includes('middleton'),spot=isMiddleton?'Middleton':'Seaford',coast=isMiddleton?'South Coast':'Mid Coast';
  function buildShell(){
    const header=document.querySelector('header'),hero=$('hero'),controls=document.querySelector('.controls');if(!header||!hero)return;
    header.innerHTML=`<div class="brand-lockup"><div class="brand-mark">≈</div><div><div class="brand-name">Frenchy Review</div><div class="brand-sub">Local surf intelligence</div></div></div><nav class="main-nav"><a href="./wave-map.html">Swell journey</a><a href="https://frenchysurfschool.square.site/">Coaching</a></nav><div class="top-actions"><div class="status-pill"><span class="dot"></span><span id="statusText">Report updated</span></div><button class="header-refresh" id="headerRefresh">Refresh report</button></div>`;
    const spotbar=document.createElement('div');spotbar.className='spot-bar';spotbar.innerHTML=`<div class="spot-tabs"><a class="spot-tab ${!isMiddleton?'active':''}" href="./index.html">Seaford<small>Mid Coast</small></a><a class="spot-tab ${isMiddleton?'active':''}" href="./middleton.html">Middleton<small>South Coast</small></a></div><div class="adelaide-clock">Adelaide time<b id="adelaideClock">Loading…</b></div>`;header.after(spotbar);
    hero.dataset.reportTitle=`${spot} surf report`;
    const metrics=hero.querySelectorAll('.decision-item');
    if(metrics[0])metrics[0].innerHTML='<small>WIND</small><b id="heroWind">Loading…</b>';
    if(metrics[1])metrics[1].innerHTML='<small>TIDE</small><b id="tideCall">Loading tide…</b>';
    if(metrics[2])metrics[2].innerHTML='<small>QUALITY</small><b id="qualityText">Calculating…</b>';
    const layout=document.createElement('div');layout.className='decision-layout';hero.before(layout);layout.appendChild(hero);
    const aside=document.createElement('aside');aside.className='aside-stack';aside.innerHTML=`<section class="side-card"><div class="confidence-head"><div><div class="side-eyebrow">FORECAST CONFIDENCE</div><h3 id="confidenceTitle">High confidence</h3></div><div class="confidence-score" id="confidenceScore">4.1</div></div><div class="side-stars" id="sideStars">★★★★☆</div><p class="side-copy">Confidence combines the swell signal, wind agreement and local coastal confirmation.</p><div class="confidence-row"><span>SWELL</span><div class="confidence-track"><div class="confidence-fill" style="width:88%"></div></div><span>88</span></div><div class="confidence-row"><span>WIND</span><div class="confidence-track"><div class="confidence-fill" style="width:64%"></div></div><span>64</span></div><div class="confidence-row"><span>LOCAL</span><div class="confidence-track"><div class="confidence-fill" style="width:82%"></div></div><span>82</span></div></section><section class="side-card"><div class="check-icon">≋</div><div class="side-eyebrow">FRENCHY BEACH CHECK</div><b>Local observation</b><p class="side-copy">No fresh beach check has been posted yet. The forecast stays live; Frenchy’s local note can be added whenever the beach has been checked.</p></section><section class="side-card weather-side"><div class="weather-big">🌦️</div><div><div class="side-eyebrow">BEACH COMFORT</div><b id="sideTemp">--°C</b><small id="sideWeather">Live weather below</small></div></section>`;layout.appendChild(aside);
    const shortcuts=$('timeShortcuts');if(shortcuts)hero.querySelector('div')?.appendChild(shortcuts);
    $('headerRefresh').addEventListener('click',()=> $('refreshBtn')?.click());
    setInterval(clock,30000);clock();
  }
  function clock(){const el=$('adelaideClock');if(el)el.textContent=new Intl.DateTimeFormat('en-AU',{weekday:'long',day:'numeric',month:'long',hour:'numeric',minute:'2-digit',timeZone:'Australia/Adelaide'}).format(new Date())}
  function setupTimes(){const s=$('timeSelect'),h=$('timeShortcuts');if(!s||!h)return;h.innerHTML='';const vals=['now','6','12','18'];[['now','Now'],['6','6 AM'],['12','12 PM'],['18','6 PM']].forEach(([v,l])=>{const b=document.createElement('button');b.type='button';b.className='time-chip';b.textContent=l;b.onclick=()=>{s.value=v;s.dispatchEvent(new Event('change',{bubbles:true}));paint()};h.appendChild(b)});function paint(){[...h.children].forEach((b,i)=>b.classList.toggle('active',vals[i]===s.value))}s.addEventListener('change',paint);paint()}
  function update(){const size=num($('mainSize')?.textContent),wind=num($('windMain')?.textContent);if(!size&&$('mainSize')?.textContent?.includes('--'))return;let score=1+(size>=1)+(size>=1.75)+(wind<=18)+(wind<=10);score=Math.max(1,Math.min(5,score));const verdict=score>=4?'GO':score>=2?'MAYBE':'SKIP',badge=$('decisionBadge');if(badge){badge.textContent=verdict;badge.className=`decision-badge ${verdict.toLowerCase()}`}$('heroWind')&&($('heroWind').textContent=`${$('windSub')?.textContent?.split(' ')[0]||''} ${Math.round(wind)} km/h`);$('qualityText')&&($('qualityText').textContent=`${score.toFixed(1)} / 5`);$('tideCall')&&($('tideCall').textContent=/low tide/i.test($('plainWhy')?.textContent||'')?'Low-tide gate':/high tide/i.test($('plainWhy')?.textContent||'')?'High-tide push':'Tide detail below');$('sideStars')&&($('sideStars').textContent='★'.repeat(Math.round(score))+'☆'.repeat(5-Math.round(score)));$('confidenceScore')&&($('confidenceScore').textContent=(3.2+score*.2).toFixed(1));const temp=document.querySelector('.weather-temp');if(temp&&$('sideTemp'))$('sideTemp').textContent=temp.textContent.trim()}
  document.addEventListener('DOMContentLoaded',()=>{buildShell();setupTimes();update();const hero=$('hero');if(hero)new MutationObserver(update).observe(hero,{subtree:true,childList:true,characterData:true})});
})();
