(() => {
  const $ = id => document.getElementById(id);
  const numberFrom = text => Number(String(text || '').match(/[\d.]+/)?.[0] || 0);
  function recommendation(size, wind) { if(size<.75)return'High-volume board';if(size<1.75)return'Longboard or foamie';if(size<2.75)return'Fish, midlength or longboard';return wind>25?'Stable board · mind the wind':'Shortboard or performance board'; }
  function updateDecision(){const size=numberFrom($('mainSize')?.textContent),wind=numberFrom($('windMain')?.textContent);if(!size&&$('mainSize')?.textContent?.includes('--'))return;let score=1;if(size>=1)score++;if(size>=1.75)score++;if(wind<=18)score++;if(wind<=10)score++;score=Math.max(1,Math.min(5,score));const verdict=score>=4?'GO':score>=2?'MAYBE':'SKIP',badge=$('decisionBadge');if(badge){badge.textContent=verdict;badge.className=`decision-badge ${verdict.toLowerCase()}`}$('qualityStars')&&($('qualityStars').textContent='★'.repeat(score)+'☆'.repeat(5-score));$('qualityText')&&($('qualityText').textContent=`${score}/5 · ${score>=4?'Worth the paddle':score>=2?'Check it first':'Save your energy'}`);$('boardCall')&&($('boardCall').textContent=recommendation(size,wind));$('confidenceCall')&&($('confidenceCall').textContent=wind<=25?'High · live data aligned':'Medium · wind may shift it');const why=$('plainWhy')?.textContent||'';$('tideCall')&&($('tideCall').textContent=/low tide/i.test(why)?'Low-tide gate':/high tide/i.test(why)?'High-tide push':'See today’s tide below')}
  function setupTimeChips(){const select=$('timeSelect'),host=$('timeShortcuts');if(!select||!host||host.children.length)return;const values=['now','6','12','18'];[['now','Now'],['6','6 AM'],['12','12 PM'],['18','6 PM']].forEach(([value,label])=>{const button=document.createElement('button');button.type='button';button.className='time-chip';button.textContent=label;button.addEventListener('click',()=>{select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));paint()});host.appendChild(button)});const paint=()=>host.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',values[i]===select.value));select.addEventListener('change',paint);paint()}
  function setupShare(){$('shareReportBtn')?.addEventListener('click',async()=>{const text=`${document.title}: ${$('mainSize')?.textContent||''} ft · ${$('windMain')?.textContent||''} wind`;try{if(navigator.share)await navigator.share({title:document.title,text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);$('shareReportBtn').textContent='Copied!'}}catch(_){}})}
  document.addEventListener('DOMContentLoaded',()=>{setupTimeChips();setupShare();updateDecision();const target=$('hero');if(target)new MutationObserver(updateDecision).observe(target,{subtree:true,childList:true,characterData:true})});
})();
